"""
Runtime TCAD lookup helper for the Satellite Simulation.

Place this file in:
    /Users/kyuhyunkim/DryDock/tcad/tcad_lookup_runtime.py

It reads the offline lookup table generated by generate_tcad_lookup_table.py and
builds a fast SQLite cache. The VPython simulation should load this once at
startup, then call lookup_sensor_degradation(...) during telemetry updates.

Why SQLite?
    The generated JSON table can have millions of entries. Scanning that JSON at
    10 Hz would be too slow. This helper converts the JSON into an indexed
    cache once, then each lookup is a direct key query.
"""

from __future__ import annotations

import json
import math
import os
import sqlite3
import time
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional, Tuple

# These defaults match the improved generator. If the JSON header is unavailable,
# the runtime can still quantize values correctly.
DEFAULT_GRIDS: Dict[str, List[float]] = {
    "cumulative_dose_levels_msv": [0, 2, 5, 10, 25, 50, 100, 200, 400, 800],
    "dose_rate_levels_msv_per_day": [0.05, 0.35, 1, 2, 8, 20, 50, 100],
    "particle_flux_levels_pfu": [1, 10, 50, 200, 1000, 5000, 20000],
    "temperature_levels_c": [-40, -20, 0, 25, 50, 75, 100],
    "shielding_levels_mm_al": [0.0, 0.5, 2.5, 5.0, 10.0, 15.0],
    "sun_exposure_levels": [0.0, 0.25, 0.5, 1.0],
    "trapped_belt_factors": [0.15, 0.35, 0.70, 1.00],
}

DEFAULT_SENSOR_TYPES = [
    "visible_camera_cmos",
    "star_tracker_cmos",
    "voltage_sensor_adc",
    "thermal_sensor_readout",
    "rf_frontend",
    "solar_panel_current_sensor",
    "communication_radio",
    "command_decoder",
    "onboard_processor",
]

SIM_SENSOR_TO_TCAD_SENSOR = {
    "camera_sensor": "visible_camera_cmos",
    "visible_camera": "visible_camera_cmos",
    "visible_camera_cmos": "visible_camera_cmos",
    "attitude_state": "star_tracker_cmos",
    "star_tracker": "star_tracker_cmos",
    "star_tracker_cmos": "star_tracker_cmos",
    "voltage_sensors": "voltage_sensor_adc",
    "voltage_sensor_adc": "voltage_sensor_adc",
    "thermal_profile": "thermal_sensor_readout",
    "thermal_sensor_readout": "thermal_sensor_readout",
    "passive_rf": "rf_frontend",
    "rf_frontend": "rf_frontend",
    "solar_panel_system": "solar_panel_current_sensor",
    "solar_panel_current_sensor": "solar_panel_current_sensor",
    "communication_link": "communication_radio",
    "communication_radio": "communication_radio",
    "command_decoder": "command_decoder",
    "onboard_processor": "onboard_processor",
}

REGION_TO_TRAPPED_BELT_FACTOR = {
    "low_earth_orbit": 0.35,
    "inner_van_allen_region": 1.00,
    "outer_van_allen_region": 0.70,
    "high_earth_orbit": 0.35,
    "quiet_or_eclipse_low_belt": 0.15,
}


def clamp(value: float, low: float, high: float) -> float:
    return max(low, min(high, value))


def _fmt_key_value(value: float) -> str:
    return f"{float(value):.8g}"


def _make_key(
    sensor_type: str,
    cumulative_dose_msv: float,
    dose_rate_msv_per_day: float,
    particle_flux_pfu: float,
    temperature_c: float,
    shielding_mm_aluminum: float,
    sun_exposure_factor: float,
    trapped_belt_factor: float,
) -> str:
    return "|".join(
        [
            sensor_type,
            _fmt_key_value(cumulative_dose_msv),
            _fmt_key_value(dose_rate_msv_per_day),
            _fmt_key_value(particle_flux_pfu),
            _fmt_key_value(temperature_c),
            _fmt_key_value(shielding_mm_aluminum),
            _fmt_key_value(sun_exposure_factor),
            _fmt_key_value(trapped_belt_factor),
        ]
    )


def nearest_grid_value(value: float, grid: Iterable[float]) -> float:
    values = list(grid)
    if not values:
        return float(value)
    return float(min(values, key=lambda x: abs(float(x) - float(value))))


def sensor_type_for_sim_field(sim_sensor_name: str) -> str:
    return SIM_SENSOR_TO_TCAD_SENSOR.get(sim_sensor_name, sim_sensor_name)


def region_to_trapped_belt_factor(region: Optional[str]) -> float:
    return REGION_TO_TRAPPED_BELT_FACTOR.get(region or "", 0.35)


def find_default_lookup_path() -> Optional[str]:
    candidates = [
        os.environ.get("TCAD_LOOKUP_TABLE_PATH"),
        os.path.join(os.getcwd(), "tcad_lookup_table.json"),
        os.path.join(os.getcwd(), "tcad", "tcad_lookup_table.json"),
        "/Users/kyuhyunkim/DryDock/tcad/tcad_lookup_table.json",
    ]
    for path in candidates:
        if path and os.path.exists(path):
            return path
    return None


@dataclass
class LookupResult:
    enabled: bool
    source: str
    sensor_type: str
    quantized_inputs: Dict[str, float]
    outputs: Dict[str, Any]
    note: str = ""

    def to_payload(self) -> Dict[str, Any]:
        return {
            "enabled": self.enabled,
            "source": self.source,
            "sensor_type": self.sensor_type,
            "quantized_inputs": self.quantized_inputs,
            "outputs": self.outputs,
            "note": self.note,
        }


class TcadLookup:
    def __init__(self, json_path: str, sqlite_path: Optional[str] = None, auto_build_cache: bool = True):
        self.json_path = os.path.abspath(json_path)
        self.sqlite_path = sqlite_path or self.json_path + ".sqlite"
        self.auto_build_cache = auto_build_cache
        self.enabled = False
        self.header: Dict[str, Any] = {}
        self.grids: Dict[str, List[float]] = dict(DEFAULT_GRIDS)
        self.sensor_types: List[str] = list(DEFAULT_SENSOR_TYPES)
        self.last_load_note = "not loaded"
        self._conn: Optional[sqlite3.Connection] = None

        if not os.path.exists(self.json_path):
            self.last_load_note = f"lookup JSON not found: {self.json_path}"
            return

        try:
            if self.auto_build_cache and not self._cache_is_ready():
                self.build_sqlite_cache()
            self._open_cache()
            self.enabled = True
            self.last_load_note = f"loaded indexed TCAD lookup cache: {self.sqlite_path}"
        except Exception as exc:
            self.enabled = False
            self.last_load_note = f"TCAD lookup cache unavailable; fallback equations active ({exc})"

    def close(self) -> None:
        if self._conn is not None:
            self._conn.close()
            self._conn = None

    def _cache_is_ready(self) -> bool:
        if not os.path.exists(self.sqlite_path):
            return False
        try:
            conn = sqlite3.connect(self.sqlite_path)
            cur = conn.cursor()
            cur.execute("SELECT value FROM meta WHERE key='source_json_mtime'")
            row = cur.fetchone()
            cur.execute("SELECT COUNT(*) FROM entries")
            count = cur.fetchone()[0]
            conn.close()
            return row is not None and count > 0 and float(row[0]) >= os.path.getmtime(self.json_path)
        except Exception:
            return False

    def _open_cache(self) -> None:
        self._conn = sqlite3.connect(self.sqlite_path)
        self._conn.execute("PRAGMA query_only = ON")
        self.header = self._read_meta_json("header", {})
        grid = self._read_meta_json("input_grid", {})
        if grid:
            self._load_grids_from_header(grid)

    def _read_meta_json(self, key: str, default: Any) -> Any:
        if self._conn is None:
            return default
        cur = self._conn.cursor()
        cur.execute("SELECT value FROM meta WHERE key=?", (key,))
        row = cur.fetchone()
        if not row:
            return default
        try:
            return json.loads(row[0])
        except Exception:
            return default

    def _load_grids_from_header(self, input_grid: Dict[str, Any]) -> None:
        for key in DEFAULT_GRIDS:
            if key in input_grid and isinstance(input_grid[key], list):
                self.grids[key] = [float(v) for v in input_grid[key]]
        sensor_types = input_grid.get("sensor_types")
        if isinstance(sensor_types, list) and sensor_types:
            self.sensor_types = [str(v) for v in sensor_types]

    def _read_header_before_entries(self) -> Dict[str, Any]:
        marker = '"entries"'
        buffer = ""
        with open(self.json_path, "r") as f:
            while True:
                chunk = f.read(1024 * 1024)
                if not chunk:
                    break
                buffer += chunk
                idx = buffer.find(marker)
                if idx >= 0:
                    prefix = buffer[:idx].rstrip()
                    if prefix.endswith(","):
                        prefix = prefix[:-1]
                    try:
                        header = json.loads(prefix + "}\n")
                    except Exception:
                        header = {}
                    return header
                # The header is small; if something unusual happens, avoid unbounded growth.
                if len(buffer) > 50 * 1024 * 1024:
                    break
        return {}

    def _stream_entries(self):
        decoder = json.JSONDecoder()
        with open(self.json_path, "r") as f:
            # Move to the start of the entries array.
            marker = '"entries"'
            lookback = ""
            found_marker = False
            while not found_marker:
                chunk = f.read(1024 * 1024)
                if not chunk:
                    return
                lookback += chunk
                idx = lookback.find(marker)
                if idx >= 0:
                    f.seek(f.tell() - len(lookback) + idx + len(marker))
                    found_marker = True
                elif len(lookback) > len(marker) + 64:
                    lookback = lookback[-(len(marker) + 64):]

            # Find '[' after the marker.
            char = f.read(1)
            while char and char != "[":
                char = f.read(1)
            if not char:
                return

            buffer = ""
            eof = False
            while True:
                if not eof and len(buffer) < 1024 * 512:
                    chunk = f.read(1024 * 1024)
                    if chunk:
                        buffer += chunk
                    else:
                        eof = True

                buffer = buffer.lstrip()
                if not buffer and eof:
                    break
                if buffer.startswith("]"):
                    break
                if buffer.startswith(","):
                    buffer = buffer[1:]
                    continue

                try:
                    obj, end = decoder.raw_decode(buffer)
                    yield obj
                    buffer = buffer[end:]
                except json.JSONDecodeError:
                    if eof:
                        break
                    chunk = f.read(1024 * 1024)
                    if chunk:
                        buffer += chunk
                    else:
                        eof = True

    def build_sqlite_cache(self) -> None:
        os.makedirs(os.path.dirname(self.sqlite_path) or ".", exist_ok=True)
        temp_sqlite = self.sqlite_path + ".tmp"
        if os.path.exists(temp_sqlite):
            os.remove(temp_sqlite)

        header = self._read_header_before_entries()
        input_grid = header.get("input_grid", {}) if isinstance(header, dict) else {}
        if isinstance(input_grid, dict):
            self._load_grids_from_header(input_grid)

        conn = sqlite3.connect(temp_sqlite)
        cur = conn.cursor()
        cur.execute("PRAGMA journal_mode = OFF")
        cur.execute("PRAGMA synchronous = OFF")
        cur.execute("CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)")
        cur.execute("CREATE TABLE entries (key TEXT PRIMARY KEY, outputs_json TEXT NOT NULL)")
        cur.execute("INSERT INTO meta(key, value) VALUES (?, ?)", ("header", json.dumps(header)))
        cur.execute("INSERT INTO meta(key, value) VALUES (?, ?)", ("input_grid", json.dumps(input_grid or self.grids)))
        cur.execute("INSERT INTO meta(key, value) VALUES (?, ?)", ("source_json_path", self.json_path))
        cur.execute("INSERT INTO meta(key, value) VALUES (?, ?)", ("source_json_mtime", str(os.path.getmtime(self.json_path))))
        cur.execute("INSERT INTO meta(key, value) VALUES (?, ?)", ("built_unix_time_s", str(time.time())))

        batch: List[Tuple[str, str]] = []
        count = 0
        for entry in self._stream_entries():
            try:
                sensor_type = str(entry["sensor_type"])
                inputs = entry["inputs"]
                key = _make_key(
                    sensor_type,
                    inputs.get("cumulative_dose_msv", 0.0),
                    inputs.get("dose_rate_msv_per_day", 0.0),
                    inputs.get("particle_flux_pfu", 0.0),
                    inputs.get("temperature_c", 25.0),
                    inputs.get("shielding_mm_aluminum", 2.5),
                    inputs.get("sun_exposure_factor", 1.0),
                    inputs.get("trapped_belt_factor", 0.35),
                )
                batch.append((key, json.dumps(entry.get("outputs", {}), separators=(",", ":"))))
                count += 1
                if len(batch) >= 5000:
                    cur.executemany("INSERT OR REPLACE INTO entries(key, outputs_json) VALUES (?, ?)", batch)
                    conn.commit()
                    batch.clear()
                    if count % 100000 == 0:
                        print(f"  indexed {count} TCAD lookup entries")
            except Exception:
                continue

        if batch:
            cur.executemany("INSERT OR REPLACE INTO entries(key, outputs_json) VALUES (?, ?)", batch)
            conn.commit()
        cur.execute("INSERT OR REPLACE INTO meta(key, value) VALUES (?, ?)", ("entry_count", str(count)))
        conn.commit()
        conn.close()

        os.replace(temp_sqlite, self.sqlite_path)
        print(f"Built TCAD SQLite cache with {count} entries: {self.sqlite_path}")

    def lookup(
        self,
        sensor_type: str,
        cumulative_dose_msv: float,
        dose_rate_msv_per_day: float,
        particle_flux_pfu: float,
        temperature_c: float,
        shielding_mm_aluminum: float,
        sun_exposure_factor: float,
        trapped_belt_factor: float,
    ) -> LookupResult:
        sensor_type = sensor_type_for_sim_field(sensor_type)
        quantized = {
            "cumulative_dose_msv": nearest_grid_value(cumulative_dose_msv, self.grids["cumulative_dose_levels_msv"]),
            "dose_rate_msv_per_day": nearest_grid_value(dose_rate_msv_per_day, self.grids["dose_rate_levels_msv_per_day"]),
            "particle_flux_pfu": nearest_grid_value(particle_flux_pfu, self.grids["particle_flux_levels_pfu"]),
            "temperature_c": nearest_grid_value(temperature_c, self.grids["temperature_levels_c"]),
            "shielding_mm_aluminum": nearest_grid_value(shielding_mm_aluminum, self.grids["shielding_levels_mm_al"]),
            "sun_exposure_factor": nearest_grid_value(sun_exposure_factor, self.grids["sun_exposure_levels"]),
            "trapped_belt_factor": nearest_grid_value(trapped_belt_factor, self.grids["trapped_belt_factors"]),
        }

        if self.enabled and self._conn is not None:
            key = _make_key(
                sensor_type,
                quantized["cumulative_dose_msv"],
                quantized["dose_rate_msv_per_day"],
                quantized["particle_flux_pfu"],
                quantized["temperature_c"],
                quantized["shielding_mm_aluminum"],
                quantized["sun_exposure_factor"],
                quantized["trapped_belt_factor"],
            )
            cur = self._conn.cursor()
            cur.execute("SELECT outputs_json FROM entries WHERE key=?", (key,))
            row = cur.fetchone()
            if row:
                return LookupResult(True, "tcad_lookup_sqlite_nearest_grid", sensor_type, quantized, json.loads(row[0]))

        return LookupResult(False, "fallback_equation", sensor_type, quantized, fallback_degradation_outputs(sensor_type, **quantized), self.last_load_note)


def fallback_degradation_outputs(
    sensor_type: str,
    cumulative_dose_msv: float,
    dose_rate_msv_per_day: float,
    particle_flux_pfu: float,
    temperature_c: float,
    shielding_mm_aluminum: float,
    sun_exposure_factor: float,
    trapped_belt_factor: float,
) -> Dict[str, Any]:
    shield = 0.5 ** (max(0.0, shielding_mm_aluminum) / 7.0)
    direct_solar = 0.25 + 0.75 * clamp(sun_exposure_factor, 0.0, 1.0)
    severity = shield * (0.55 + 0.45 * trapped_belt_factor) * direct_solar
    temp_stress = max(0.0, temperature_c - 40.0) / 60.0

    sensor_mult = {
        "visible_camera_cmos": 1.35,
        "star_tracker_cmos": 1.45,
        "rf_frontend": 1.15,
        "communication_radio": 1.18,
        "voltage_sensor_adc": 0.85,
        "thermal_sensor_readout": 0.75,
        "solar_panel_current_sensor": 0.85,
        "command_decoder": 1.10,
        "onboard_processor": 1.25,
    }.get(sensor_type, 1.0)

    health_loss_per_day = clamp(sensor_mult * severity * (0.015 * dose_rate_msv_per_day + 0.000004 * particle_flux_pfu + 0.25 * temp_stress), 0.0, 8.0)
    noise_growth_per_day = clamp(sensor_mult * severity * (0.0006 * dose_rate_msv_per_day + 0.0000008 * particle_flux_pfu + 0.015 * temp_stress), 0.0, 0.5)
    bias_drift_per_day = clamp(sensor_mult * severity * (0.00025 * dose_rate_msv_per_day + 0.006 * temp_stress), 0.0, 0.25)
    seu_probability_per_day = clamp(sensor_mult * shield * (0.00001 * particle_flux_pfu + 0.0004 * dose_rate_msv_per_day), 0.0, 0.95)
    confidence = clamp(1.0 - 0.0012 * cumulative_dose_msv - health_loss_per_day * 0.04 - noise_growth_per_day * 0.5 - seu_probability_per_day * 0.3, 0.05, 0.99)

    dark_current_multiplier = 1.0 + max(0.0, cumulative_dose_msv) * 0.0008 + max(0.0, temperature_c - 25.0) * 0.015
    hot_pixel_fraction = clamp(0.00002 + cumulative_dose_msv * 0.0000015 + particle_flux_pfu * 0.00000001, 0.0, 0.20)
    dead_pixel_fraction = clamp(0.000005 + cumulative_dose_msv * 0.00000045, 0.0, 0.10)
    frame_corruption_probability = clamp(seu_probability_per_day * 0.22 + particle_flux_pfu * 0.000002, 0.0, 0.75)

    return {
        "sensor_effects": {
            "sensor_confidence": round(confidence, 6),
            "health_loss_per_day": round(health_loss_per_day, 8),
            "noise_growth_per_day": round(noise_growth_per_day, 8),
            "bias_drift_per_day": round(bias_drift_per_day, 8),
            "seu_probability_per_day": round(seu_probability_per_day, 8),
            "trust_level": "normal" if confidence >= 0.85 else "slightly_downweighted" if confidence >= 0.65 else "heavily_downweighted" if confidence >= 0.40 else "quarantine_sensor_data",
            "safe_to_use_for_autonomous_control": bool(confidence >= 0.65),
        },
        "camera_effects": {
            "dark_current_multiplier": round(dark_current_multiplier, 6),
            "hot_pixel_fraction": round(hot_pixel_fraction, 8),
            "dead_pixel_fraction": round(dead_pixel_fraction, 8),
            "frame_corruption_probability": round(frame_corruption_probability, 8),
        },
        "rf_effects": {
            "gain_loss_db": round(clamp(health_loss_per_day * 0.14, 0.0, 8.0), 6),
            "noise_floor_shift_db": round(clamp(noise_growth_per_day * 8.0, 0.0, 12.0), 6),
        },
        "readout_effects": {
            "offset_drift_fraction": round(bias_drift_per_day, 8),
            "bad_sample_probability": round(seu_probability_per_day * 0.35, 8),
        },
    }


def load_tcad_lookup(json_path: Optional[str] = None, sqlite_path: Optional[str] = None, auto_build_cache: bool = True) -> TcadLookup:
    path = json_path or find_default_lookup_path()
    if not path:
        # Return a disabled lookup object pointed at a likely default path.
        lookup = TcadLookup.__new__(TcadLookup)
        lookup.json_path = json_path or "/Users/kyuhyunkim/DryDock/tcad/tcad_lookup_table.json"
        lookup.sqlite_path = sqlite_path or lookup.json_path + ".sqlite"
        lookup.auto_build_cache = auto_build_cache
        lookup.enabled = False
        lookup.header = {}
        lookup.grids = dict(DEFAULT_GRIDS)
        lookup.sensor_types = list(DEFAULT_SENSOR_TYPES)
        lookup.last_load_note = "tcad_lookup_table.json not found; fallback equations active"
        lookup._conn = None
        return lookup
    return TcadLookup(path, sqlite_path=sqlite_path, auto_build_cache=auto_build_cache)


def lookup_sensor_degradation(
    lookup: Optional[TcadLookup],
    sensor_type: str,
    cumulative_dose_msv: float,
    dose_rate_msv_per_day: float,
    particle_flux_pfu: float,
    temperature_c: float,
    shielding_mm_aluminum: float,
    sun_exposure_factor: float,
    trapped_belt_factor: float,
) -> Dict[str, Any]:
    if lookup is None:
        sensor_type = sensor_type_for_sim_field(sensor_type)
        quantized = {
            "cumulative_dose_msv": cumulative_dose_msv,
            "dose_rate_msv_per_day": dose_rate_msv_per_day,
            "particle_flux_pfu": particle_flux_pfu,
            "temperature_c": temperature_c,
            "shielding_mm_aluminum": shielding_mm_aluminum,
            "sun_exposure_factor": sun_exposure_factor,
            "trapped_belt_factor": trapped_belt_factor,
        }
        return LookupResult(False, "fallback_equation_no_lookup_loaded", sensor_type, quantized, fallback_degradation_outputs(sensor_type, **quantized)).to_payload()
    return lookup.lookup(
        sensor_type=sensor_type,
        cumulative_dose_msv=cumulative_dose_msv,
        dose_rate_msv_per_day=dose_rate_msv_per_day,
        particle_flux_pfu=particle_flux_pfu,
        temperature_c=temperature_c,
        shielding_mm_aluminum=shielding_mm_aluminum,
        sun_exposure_factor=sun_exposure_factor,
        trapped_belt_factor=trapped_belt_factor,
    ).to_payload()

if __name__ == "__main__":
    path = find_default_lookup_path() or "/Users/kyuhyunkim/DryDock/tcad/tcad_lookup_table.json"
    print(f"Preparing TCAD lookup runtime cache for: {path}")
    runtime = load_tcad_lookup(path, auto_build_cache=True)
    print(runtime.last_load_note)
    if runtime.enabled:
        sample = lookup_sensor_degradation(
            runtime,
            sensor_type="visible_camera_cmos",
            cumulative_dose_msv=10.0,
            dose_rate_msv_per_day=8.0,
            particle_flux_pfu=1000.0,
            temperature_c=25.0,
            shielding_mm_aluminum=2.5,
            sun_exposure_factor=1.0,
            trapped_belt_factor=0.70,
        )
        print("Sample lookup sensor confidence:", sample.get("outputs", {}).get("sensor_effects", {}).get("sensor_confidence"))
    runtime.close()
